# Makefile for writer program
# Author: Generated for assignment-2

CC = gcc
CFLAGS = -Wall -Werror -std=c99
TARGET = writer
SOURCE = writer.c


# Default target (make)
$(TARGET): $(SOURCE)
	$(CROSS_COMPILE)$(CC) $(CFLAGS) -o $(TARGET) $(SOURCE)

# Clean target
clean:
	rm -f $(TARGET) *.o


